### ISSUE TITLE
Error scanning to PDF

### ISSUE THREAD

**Issue by AxelRHD** [sbs20/scanservjs#53] opened 2020-08-27 18:03 UTC
First: thank you for the great work! I love that project.

But I can't scan to PDF getting the error below:

command failed: /usr/bin/scanimage -d "genesys:libusb:003:002" --mode "color" --resolution 300 -l 0 -t 0 -x 210 -y 297 --format tiff --brightness 0 --contrast 0 | convert - pdf:- > "./data/output/scan_2020-08-27 18.01.18.pdf" convert-im6.q16: attempt to perform an operation not allowed by the security policy `pdf' @ error/constitute.c/iscoderauthorized/408.

I do not really understand that error. Is it a problem "inside" or "itside" of the container?

**Comment by JnCrMx** [comment] 2020-08-27 18:16
Hi,

that seems to be a duplicate of #50 and is definitely related to the container. There is already a fix in #51 which was already merged into the ``development`` branch.

I don't know about @sbs20's plans, but I guess after some testing it will be in ``master``.

**Comment by AxelRHD** [comment] 2020-08-27 18:22
Oh. Thank you for the fast reply. Sounds like promising news.

**Comment by sbs20** [comment] 2020-08-27 18:28
My bad. I wasn't paying attention when I merged and thought it had gone into master. I'll sort this tomorrow, or if someone else can create a PR into master for just that commit, I can merge later.

**Comment by sbs20** [comment] 2020-08-28 14:39
Hopefully this is resolved now.

**Closed by sbs20** 2020-08-28 14:39 UTC
