### ISSUE TITLE
Set 'scanimageAdditionalArguments' per device

### ISSUE THREAD

**Issue by tefracky** [sbs20/scanservjs#493] opened 2022-12-14 07:51 UTC
**Describe the bug**
I have two scanners, a Fujitsu and a Samsung. For the Fujitsu, I have to set 
```
config.scanimageAdditionalArguments = {
   '--page-height': 297
 };
```

in order to scan the full page. But unfortunately, then I am unable to use the Samsung scanner (`unrecognized option '--page-height'`). Is it possible to set the page-height option per scanner? Maybe in this section:

```
afterDevices(devices) {
  /**
   * Example code below
   */
  devices
    .filter(d => d.id.includes('fujitsu'))
    .forEach(device => {
      device.features['--mode'].default = 'Lineart';
      device.features['--resolution'].default = 300;
    //   device.features['--resolution'].options = [150, 300, 600];
    //   device.features['--brightness'].default = 10;
    //   device.features['--contrast'].default = 20;

      device.features['-l'].limits = [5, 215];
      device.features['-t'].limits = [0, 297];
      device.features['-x'].limits = [0, 210];
      device.features['-y'].limits = [0, 297];

      device.features['-x'].default = 210;
      device.features['-y'].default = 297;
    });
  devices
    .filter(d => d.id.includes('samsung'))
    .forEach(device => {
      device.features['--mode'].default = 'Lineart';
      device.features['--resolution'].default = 300;
    //   device.features['--resolution'].options = [150, 300, 600];
    //   device.features['--brightness'].default = 10;
    //   device.features['--contrast'].default = 20;

      device.features['-l'].limits = [0, 210]
      device.features['-t'].limits = [0, 297];
      device.features['-x'].limits = [0, 210];
      device.features['-y'].limits = [0, 297];

      device.features['-x'].default = 210;
      device.features['-y'].default = 297;
    });
}
```

**Server (please complete the following information):**
 - OS: Debian 11 (bullseye)
 - Node version: 19.2.0
 - NPM version: 9.1.3

**Logs**
```
Dez 14 08:43:46 Raspi-4 server.js[415628]: [2022-12-14T07:43:46.133Z] DEBUG (Http): request:  {
Dez 14 08:43:46 Raspi-4 server.js[415628]:   method: 'POST',
Dez 14 08:43:46 Raspi-4 server.js[415628]:   path: '/scanner/preview',
Dez 14 08:43:46 Raspi-4 server.js[415628]:   body: {
Dez 14 08:43:46 Raspi-4 server.js[415628]:     version: '2.21.0',
Dez 14 08:43:46 Raspi-4 server.js[415628]:     params: {
Dez 14 08:43:46 Raspi-4 server.js[415628]:       deviceId: 'xerox_mfp:tcp 192.168.2.157',
Dez 14 08:43:46 Raspi-4 server.js[415628]:       resolution: 300,
Dez 14 08:43:46 Raspi-4 server.js[415628]:       top: 0,
Dez 14 08:43:46 Raspi-4 server.js[415628]:       left: 0,
Dez 14 08:43:46 Raspi-4 server.js[415628]:       width: 210,
Dez 14 08:43:46 Raspi-4 server.js[415628]:       height: 148,
Dez 14 08:43:46 Raspi-4 server.js[415628]:       mode: 'Color',
Dez 14 08:43:46 Raspi-4 server.js[415628]:       source: 'Auto'
Dez 14 08:43:46 Raspi-4 server.js[415628]:     },
Dez 14 08:43:46 Raspi-4 server.js[415628]:     filters: [],
Dez 14 08:43:46 Raspi-4 server.js[415628]:     pipeline: '1 - @:pipeline.ocr | PDF (TIFF | @:pipeline.lzw-compressed)',
Dez 14 08:43:46 Raspi-4 server.js[415628]:     batch: 'none',
Dez 14 08:43:46 Raspi-4 server.js[415628]:     index: 1
Dez 14 08:43:46 Raspi-4 server.js[415628]:   }
Dez 14 08:43:46 Raspi-4 server.js[415628]: }
Dez 14 08:43:46 Raspi-4 server.js[415628]: [2022-12-14T07:43:46.229Z] DEBUG (Scanimage): {"context":{"devices":[{"id":"xerox_mfp:tcp 192.168.2.157","name":"xerox_mfp:tcp 192.168.2.157","features":{"--resolution":{"text":"--resolution 75|100|150|200|300|600dpi [150]","name":"--resolution","default":150,"parameters":"75|100|150|200|300|600dpi","options":[75,100,150,200,300,600]},"--mode":{"text":"--mode Lineart|Halftone|Gray|Color [Color]","name":"--mode","default":"Color","parameters":"Lineart|Halftone|Gray|Color","options":["Lineart","Halftone","Gray","Color"]},"--source":{"text":"--source Flatbed|ADF|Auto [Flatbed]","name":"--source","default":"Flatbed","parameters":"Flatbed|ADF|Auto","options":["Flatbed","ADF","Auto"]},"-l":{"text":"-l 0..216.069mm (in steps of 1) [0]","name":"-l","default":0,"parameters":"0..216.069mm (in steps of 1)","limits":[0,216],"interval":1},"-t":{"text":"-t 0..297.18mm (in steps of 1) [0]","name":"-t","default":0,"parameters":"0..297.18mm (in steps of 1)","limits":[0,297.1],"interval":1},"-x":{"text":"-x 0..216.069mm (in steps of 1) [216.069]","name":"-x","default":216,"parameters":"0..216.069mm (in steps of 1)","limits":[0,216],"interval":1},"-y":{"text":"-y 0..297.18mm (in steps of 1) [297.18]","name":"-y","default":297.1,"parameters":"0..297.18mm (in steps of 1)","limits":[0,297.1],"interval":1}},"string":"\nAll options specific to device `xerox_mfp:tcp 192.168.2.157':\n  Standard:\n    --resolution 75|100|150|200|300|600dpi [150]\n        Sets the resolution of the scanned image.\n    --mode Lineart|Halftone|Gray|Color [Color]\n        Selects the scan mode (e.g., lineart, monochrome, or color).\n    --highlight 30..70% (in steps of 10) [inactive]\n        Select minimum-brightness to get a white point\n    --source Flatbed|ADF|Auto [Flatbed]\n        Selects the scan source (such as a document-feeder).\n  Geometry:\n    -l 0..216.069mm (in steps of 1) [0]\n        Top-left x position of scan area.\n    -t 0..297.18mm (in steps of 1) [0]\n        Top-left y position of scan area.\n    -x 0..216.069mm (in steps of 1) [216.069]\n        Width of scan-area.\n    -y 0..297.18mm (in steps of 1) [297.18]\n        Height of scan-area.\n\n"}],"version":"2.21.0","diagnostics":[{"success":true,"message":"Found /usr/bin/scanimage"},{"success":true,"message":"Found /usr/bin/convert"}],"pipelines":[{"extension":"pdf","description":"1 - @:pipeline.ocr | PDF (TIFF | @:pipeline.lzw-compressed)","commands":["convert @- -compress lzw tmp-%04d.tif && ls tmp-*.tif","${config.tesseract} -l ${config.ocrLanguage} -c stream_filelist=true - - pdf > scan-0001.pdf","ls scan-*.*"]},{"extension":"pdf","description":"2 - PDF (TIFF | @:pipeline.lzw-compressed)","commands":["convert @- -compress lzw tmp-%04d.tif && ls tmp-*.tif","convert @- scan-0000.pdf","ls scan-*.*"]},{"extension":"jpg","description":"JPG | @:pipeline.high-quality","commands":["convert @- -quality 92 scan-%04d.jpg","ls scan-*.*"]},{"extension":"jpg","description":"JPG | @:pipeline.medium-quality","commands":["convert @- -quality 75 scan-%04d.jpg","ls scan-*.*"]},{"extension":"jpg","description":"JPG | @:pipeline.low-quality","commands":["convert @- -quality 50 scan-%04d.jpg","ls scan-*.*"]},{"extension":"png","description":"PNG","commands":["convert @- -quality 75 scan-%04d.png","ls scan-*.*"]},{"extension":"tif","description":"TIF | @:pipeline.uncompressed","commands":["convert @- scan-0000.tif","ls scan-*.*"]},{"extension":"tif","description":"TIF | @:pipeline.lzw-compressed","commands":["convert @- -compress lzw scan-0000.tif","ls scan-*.*"]},{"extension":"pdf","description":"PDF (TIF | @:pipeline.uncompressed)","commands":["convert @- scan-0000.pdf","ls scan-*.*"]},{"extension":"pdf","description":"PDF (TIF | @:pipeline.lzw-compressed)","commands":["convert @- -compress lzw tmp-%04d.tif && ls tmp-*.tif","convert @- scan-0000.pdf","ls scan-*.*"]},{"extension":"pdf","description":"PDF (JPG | @:pipeline.high-quality)","commands":["convert @- -quality 92 tmp-%04d.jpg && ls tmp-*.jpg","convert @- scan-0000.pdf","ls scan-*.*"]},{"extension":"pdf","description":"PDF (JPG | @:pipeline.medium-quality)","commands":["convert @- -quality 75 tmp-%04d.jpg && ls tmp-*.jpg","convert @- scan-0000.pdf","ls scan-*.*"]},{"extension":"pdf","description":"PDF (JPG | @:pipeline.low-quality)","commands":["convert @- -quality 50 tmp-%04d.jpg && ls tmp-*.jpg","convert @- scan-0000.pdf","ls scan-*.*"]},{"extension":"pdf","description":"@:pipeline.ocr | PDF (JPG | @:pipeline.high-quality)","commands":["convert @- -quality 92 tmp-%d.jpg && ls tmp-*.jpg","/usr/bin/tesseract -l deu -c stream_filelist=true - - pdf > scan-0001.pdf","ls scan-*.*"]},{"extension":"txt","description":"@:pipeline.ocr | @:pipeline.text-file","commands":["/usr/bin/tesseract -l deu -c stream_filelist=true - - txt > scan-0001.txt","ls scan-*.*"]}],"filters":[{"description":"filter.auto-level","params":"-auto-level"},{"description":"filter.threshold","params":"-channel RGB -threshold 80%"},{"description":"filter.blur","params":"-blur 1"}],"paperSizes":[{"name":"A3 (@:paper-size.portrait)","dimensions":{"x":297,"y":420}},{"name":"A4 (@:paper-size.portrait)","dimensions":{"x":210,"y":297}},{"name":"A5 (@:paper-size.portrait)","dimensions":{"x":148,"y":210}},{"name":"A5 (@:paper-size.landscape)","dimensions":{"x":210,"y":148}},{"name":"A6 (@:paper-size.portrait)","dimensions":{"x":105,"y":148}},{"name":"A6 (@:paper-size.landscape)","dimensions":{"x":148,"y":105}},{"name":"B3 (@:paper-size.portrait)","dimensions":{"x":353,"y":500}},{"name":"B4 (@:paper-size.portrait)","dimensions":{"x":250,"y":353}},{"name":"B5 (@:paper-size.portrait)","dimensions":{"x":176,"y":250}},{"name":"B5 (@:paper-size.landscape)","dimensions":{"x":250,"y":176}},{"name":"B6 (@:paper-size.portrait)","dimensions":{"x":125,"y":176}},{"name":"B6 (@:paper-size.landscape)","dimensions":{"x":176,"y":125}},{"name":"DIN D3 (@:paper-size.portrait)","dimensions":{"x":272,"y":385}},{"name":"DIN D4 (@:paper-size.portrait)","dimensions":{"x":192,"y":272}},{"name":"DIN D5 (@:paper-size.portrait)","dimensions":{"x":136,"y":192}},{"name":"DIN D5 (@:paper-size.landscape)","dimensions":{"x":192,"y":136}},{"name":"DIN D6 (@:paper-size.portrait)","dimensions":{"x":96,"y":136}},{"name":"DIN D6 (@:paper-size.landscape)","dimensions":{"x":136,"y":96}},{"name":"@:paper-size.letter (@:paper-size.portrait)","dimensions":{"x":216,"y":279}},{"name":"@:paper-size.legal (@:paper-size.portrait)","dimensions":{"x":216,"y":356}},{"name":"@:paper-size.tabloid (@:paper-size.portrait)","dimensions":{"x":279,"y":432}},{"name":"@:paper-size.ledger (@:paper-size.portrait)","dimensions":{"x":432,"y":279}},{"name":"@:paper-size.junior-legal (@:paper-size.portrait)","dimensions":{"x":127,"y":203}},{"name":"@:paper-size.half-letter (@:paper-size.portrait)","dimensions":{"x":140,"y":216}}],"batchModes":["none","manual","auto","auto-collate-standard"]},"params":{"deviceId":"xerox_mfp:tcp 192.168.2.157","resolution":100,"format":"tiff","top":0,"left":0,"width":216,"height":297.1,"mode":"Color","source":"Auto"},"filters":[],"pipeline":null,"batch":"none","index":1}
Dez 14 08:43:46 Raspi-4 server.js[415628]: [2022-12-14T07:43:46.246Z] DEBUG (Process): /usr/bin/scanimage -d 'xerox_mfp:tcp 192.168.2.157' --mode 'Color' --source 'Auto' --resolution 100 --page-height 297 -l 0 -t 0 -x 216 -y 297.1 --format 'tiff' > data/temp/~tmp-scan-0-0001.tif > data/preview/preview.tif,  undefined , {"encoding":"binary","shell":true,"maxBuffer":16384,"ignoreErrors":false}
Dez 14 08:43:47 Raspi-4 server.js[415628]: [2022-12-14T07:43:47.133Z] DEBUG (Http): request:  { method: 'POST', path: '/preview' }
Dez 14 08:43:47 Raspi-4 server.js[415628]: [2022-12-14T07:43:47.136Z] DEBUG (Process): convert - -quality 75 jpg:-,  <Buffer > , {"encoding":"binary","shell":true,"maxBuffer":16384,"ignoreErrors":true}
Dez 14 08:43:47 Raspi-4 server.js[415628]: [2022-12-14T07:43:47.435Z] ERROR (Http): Error: /usr/bin/scanimage -d 'xerox_mfp:tcp 192.168.2.157' --mode 'Color' --source 'Auto' --resolution 100 --page-height 297 -l 0 -t 0 -x 216 -y 297.1 --format 'tiff' > data/temp/~tmp-scan-0-0001.tif > data/preview/preview.tif exited with code: 1, stderr: /usr/bin/scanimage: unrecognized option '--page-height'
Dez 14 08:43:47 Raspi-4 server.js[415628]:     at ChildProcess.<anonymous> (/var/www/scanservjs/server/process.js:54:18)
Dez 14 08:43:47 Raspi-4 server.js[415628]:     at ChildProcess.emit (node:events:513:28)
Dez 14 08:43:47 Raspi-4 server.js[415628]:     at maybeClose (node:internal/child_process:1098:16)
Dez 14 08:43:47 Raspi-4 server.js[415628]:     at ChildProcess._handle.onexit (node:internal/child_process:304:5)
Dez 14 08:43:48 Raspi-4 server.js[415628]: [2022-12-14T07:43:48.475Z] DEBUG (Http): request:  { method: 'POST', path: '/preview' }
Dez 14 08:43:48 Raspi-4 server.js[415628]: [2022-12-14T07:43:48.480Z] DEBUG (Process): convert - -quality 75 jpg:-,  <Buffer > , {"encoding":"binary","shell":true,"maxBuffer":16384,"ignoreErrors":true}
```

**Comment by sbs20** [comment] 2022-12-22 00:56
Duplicate of #401

**Closed by sbs20** 2022-12-22 00:56 UTC

**Comment by tefracky** [comment] 2022-12-22 09:19
No, it is NOT a duplicate of https://github.com/sbs20/scanservjs/issues/401! It is true that I asked in this thread, but where isn't any solution.

**Comment by sbs20** [comment] 2022-12-22 09:44
As you say, you asked in that thread. And that issue was reopened immediately after your comment. I struggle to keep on top of issues as it is and having duplicates just uses up more time.

Please don't use caps again.

**Comment by tefracky** [comment] 2022-12-22 09:57
Then you should change the title, since the title is not related to the actual issue. It is also not a good practice to discuss to different issue in one thread...

**Comment by sbs20** [comment] 2022-12-22 10:58
Aww man, come on! I run this repo for free, for everyone - be nice - everyone else has been.

I accept the title isn't correct anymore, but the core issue remains - the original solution for additional arguments is incorrect - as is being able to set them for each device. So I chose to revisit the original issue in a different way hence keeping that open. I am actually working on the issue right now.

So, please, I am asking, no more caps.

**Comment by tefracky** [comment] 2022-12-22 11:36
Yes, I know you are working for free, thanks a lot (really)! And thanks a lot that you are thinking about this problem!

However, before I opened this issue, I searched for this problem and since I forgot that I already posted it under another issue, I didn't found it. So the problem is not that is not under another issue, but one must be the chance to finde it, because otherwise, new - pointless - issues will be opened.

I cannot find any caps in my last answer...

If you need any help for testing, just let me know.
