### ISSUE TITLE
Device Unspecified not found with proxy

### ISSUE THREAD

**Issue by ftp21** [sbs20/scanservjs#247] opened 2021-05-12 21:13 UTC
**Describe the bug**
If use an Nginx reverse proxy i receive "Device Unspecified not found" error, but scanner was found well.

**To Reproduce**
1. Proxy the Docker container with Nginx Proxy Manager
2. Open host
3. Click preview or scan

**Screenshots**
![image](https://user-images.githubusercontent.com/5214928/118044615-2a793a00-b377-11eb-8a1a-8f9fd14d2409.png)

**Comment by sbs20** [comment] 2021-05-12 21:18
Hi. Does #224 help? Does it work ok without nginx?

**Comment by ftp21** [comment] 2021-05-12 21:20
> Hi. Does #224 help? Does it work ok without nginx?

No now i try without proxy but with a local DNS record and i receive the same error

**Comment by sbs20** [comment] 2021-05-12 21:30
Can you share all the details asked in the bug report template? The docker logs, browser version, OS etc. It will help determine the cause.

**Comment by ftp21** [comment] 2021-05-12 21:31
> Hi. Does #224 help? Does it work ok without nginx?

Mh i try with these options and i have same problem. I removed the options and now work well. Don't know :) can be simple the Chrome cache

**Comment by sbs20** [comment] 2021-05-13 07:59
Glad it's working for you. Closing for now - if you have further issues then please provide logs / browser version and reopen.

**Closed by sbs20** 2021-05-13 07:59 UTC
